behaviors:
  BeachVolkerballCup:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 20
    max_steps: 50000000
    time_horizon: 995
    summary_freq: 55000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 125
      play_against_latest_model_ratio: 0.5
      initial_elo: 1199.995
