//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/InputActions/ControlsHeuristic.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlsHeuristic : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlsHeuristic()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlsHeuristic"",
    ""maps"": [
        {
            ""name"": ""MoveAgent"",
            ""id"": ""e10a16a6-e951-479d-b09d-4c72626adbdf"",
            ""actions"": [
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""1e3f6235-d350-4770-bf58-8e599f38bafe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Backward"",
                    ""type"": ""Button"",
                    ""id"": ""457ee21a-4868-4338-a76d-5cfc194f3da7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""ccdbb7bd-b8b3-4b0a-8def-1badba6554de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""3fc0cf94-4313-4b6b-b38a-d2c774550094"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""28776490-31c3-443e-ac72-e759e2c1d795"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f4c33bca-4c18-4f58-83d2-591c2f106472"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""902a6b89-cc34-408f-a850-5e320de0b62c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aa971fd-7fd9-4fb0-906e-0f739c412f90"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db924106-7861-4e01-9af6-a5b832859d5d"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db65daab-e956-473b-8f5a-38a4cee23be0"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf3cb9d0-26a1-4f34-a205-40820ba9950b"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""915b2435-41a2-4f1e-8281-4b412a82720d"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""173eb2b5-e5ba-4d0c-9147-486bf77d477a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95796416-7c80-4541-b193-e22146c32db1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62091fb2-212d-4e2f-8d32-9e2eb3f2e66c"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""858267e2-0016-496b-ba8b-4f1597a8f0d0"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""921242a1-09aa-46e0-8a92-a6af81902f3a"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b83fa9d-9ed8-4906-8140-110279f65403"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""596268f9-c1a7-43af-af68-3ecf8501838f"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c22375-6752-413c-bc93-c7cf9270a240"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba0a381f-4f41-41cb-9579-848b21009430"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29ef15cf-4d35-4b24-9b93-002b7df70fb2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c29f6dc4-5cbc-4b4a-be5f-561ff9fa5e5e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1d610a7-424b-4cd5-ab60-6242f5422efd"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcd35618-fff2-4a47-a396-93a0455977ad"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8915a34f-76d0-43e1-b6b4-13369967e97b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6565e8f-cb45-4137-903b-8ffeb0691499"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41152f25-c496-4a7d-84c7-28bd7f944bec"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09329f4a-3190-4912-a3f4-5cc196f68220"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bf35226-a6fd-4ca6-8608-f73d8db8f6ac"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e5b8fe3-27ee-4af7-986a-3a5cfbd80f5a"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc265605-5ca9-487f-9db6-a5cc61a31830"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9a4543e-0d7c-4a1f-a25f-eef39d7a1423"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc33ba94-a73e-4290-80c3-dcb8655e2561"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Windows10"",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Windows10"",
            ""bindingGroup"": ""Windows10"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MoveAgent
        m_MoveAgent = asset.FindActionMap("MoveAgent", throwIfNotFound: true);
        m_MoveAgent_Forward = m_MoveAgent.FindAction("Forward", throwIfNotFound: true);
        m_MoveAgent_Backward = m_MoveAgent.FindAction("Backward", throwIfNotFound: true);
        m_MoveAgent_Right = m_MoveAgent.FindAction("Right", throwIfNotFound: true);
        m_MoveAgent_Left = m_MoveAgent.FindAction("Left", throwIfNotFound: true);
        m_MoveAgent_Throw = m_MoveAgent.FindAction("Throw", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MoveAgent
    private readonly InputActionMap m_MoveAgent;
    private IMoveAgentActions m_MoveAgentActionsCallbackInterface;
    private readonly InputAction m_MoveAgent_Forward;
    private readonly InputAction m_MoveAgent_Backward;
    private readonly InputAction m_MoveAgent_Right;
    private readonly InputAction m_MoveAgent_Left;
    private readonly InputAction m_MoveAgent_Throw;
    public struct MoveAgentActions
    {
        private @ControlsHeuristic m_Wrapper;
        public MoveAgentActions(@ControlsHeuristic wrapper) { m_Wrapper = wrapper; }
        public InputAction @Forward => m_Wrapper.m_MoveAgent_Forward;
        public InputAction @Backward => m_Wrapper.m_MoveAgent_Backward;
        public InputAction @Right => m_Wrapper.m_MoveAgent_Right;
        public InputAction @Left => m_Wrapper.m_MoveAgent_Left;
        public InputAction @Throw => m_Wrapper.m_MoveAgent_Throw;
        public InputActionMap Get() { return m_Wrapper.m_MoveAgent; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveAgentActions set) { return set.Get(); }
        public void SetCallbacks(IMoveAgentActions instance)
        {
            if (m_Wrapper.m_MoveAgentActionsCallbackInterface != null)
            {
                @Forward.started -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnForward;
                @Forward.performed -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnForward;
                @Forward.canceled -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnForward;
                @Backward.started -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnBackward;
                @Backward.performed -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnBackward;
                @Backward.canceled -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnBackward;
                @Right.started -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnRight;
                @Right.performed -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnRight;
                @Right.canceled -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnRight;
                @Left.started -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnLeft;
                @Left.performed -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnLeft;
                @Left.canceled -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnLeft;
                @Throw.started -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnThrow;
                @Throw.performed -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnThrow;
                @Throw.canceled -= m_Wrapper.m_MoveAgentActionsCallbackInterface.OnThrow;
            }
            m_Wrapper.m_MoveAgentActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Forward.started += instance.OnForward;
                @Forward.performed += instance.OnForward;
                @Forward.canceled += instance.OnForward;
                @Backward.started += instance.OnBackward;
                @Backward.performed += instance.OnBackward;
                @Backward.canceled += instance.OnBackward;
                @Right.started += instance.OnRight;
                @Right.performed += instance.OnRight;
                @Right.canceled += instance.OnRight;
                @Left.started += instance.OnLeft;
                @Left.performed += instance.OnLeft;
                @Left.canceled += instance.OnLeft;
                @Throw.started += instance.OnThrow;
                @Throw.performed += instance.OnThrow;
                @Throw.canceled += instance.OnThrow;
            }
        }
    }
    public MoveAgentActions @MoveAgent => new MoveAgentActions(this);
    private int m_Windows10SchemeIndex = -1;
    public InputControlScheme Windows10Scheme
    {
        get
        {
            if (m_Windows10SchemeIndex == -1) m_Windows10SchemeIndex = asset.FindControlSchemeIndex("Windows10");
            return asset.controlSchemes[m_Windows10SchemeIndex];
        }
    }
    public interface IMoveAgentActions
    {
        void OnForward(InputAction.CallbackContext context);
        void OnBackward(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
    }
}
